server:
  port: 8001
  address: localhost

spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 5MB
  data:
    mongodb:
      uri:
        uri: mongodb://localhost/test
